from selenium.webdriver.common.by import By


class Locators:
    LOGIN_REG_BUTTON = (By.XPATH, ".//button[text()='Вход и регистрация']")
    NO_ACCOUNT_BUTTON = (By.XPATH, ".//button[text()='Нет аккаунта']")
    EMAIL_FIELD = (By.XPATH, ".//input[@placeholder='Введите Email']")
    PASSWORD_FIELD = (By.XPATH, ".//input[@placeholder='Пароль']")
    CONFIRM_PASSWORD_FIELD = (By.XPATH, ".//input[@placeholder='Повторите пароль']")
    CREATE_ACCOUNT_BUTTON = (By.XPATH, ".//button[text()='Создать аккаунт']")
    LOGIN_BUTTON = (By.XPATH, ".//button[text()='Войти']")
    LOGOUT_BUTTON = (By.XPATH, ".//button[text()='Выйти']")
    USER_NAME = (By.XPATH, ".//h3[@class='profileText name']")
    HOME_PAGE = (By.XPATH, "//*[contains(@class, 'homePage_homepage')]")
    AVATAR = (By.XPATH, "//*[@id='root']/div/div[1]/div/div[1]/button")
    BORDER_EMAIL = (By.XPATH, ".//form/div/div/div/div[@class='input_inputError__fLUP9']")
    FIELD_WITH_ERROR_SIGN = (By.XPATH, ".//div/div/form[@class='popUp_shell__LuyqR']/div/div")
    CREATE_ADVERTISEMENT = (By.XPATH, ".//button[text()='Разместить объявление']")
    MODAL_WINDOW = (By.XPATH, ".//form[@class='popUp_shell__LuyqR']")
    MODAL_WINDOW_TEXT = (By.XPATH, ".//h1[text()='Чтобы разместить объявление, авторизуйтесь']")
    NAME_AD_FIELD = (By.XPATH, ".//input[@placeholder='Название']")
    DESCRIPTION_AD_FIELD = (By.XPATH, ".//textarea[@placeholder='Описание товара']")
    COST_AD_FIELD = (By.XPATH, ".//input[@placeholder='Стоимость']")
    CATEGORY_DROP_DOWN = (By.XPATH, "//*[@id='root']/div/div[2]/div/form/div[2]/div[2]/div[1]/button")
    CATEGORY = (By.XPATH, "//*[@id='root']/div/div[2]/div/form/div[2]/div[2]/div[2]/button[2]")
    CITY_DROP_DOWN = (By.XPATH, "//*[@id='root']/div/div[2]/div/form/div[3]/div[1]/button")
    CITY = (By.XPATH, "//*[@id='root']/div/div[2]/div/form/div[3]/div[2]/button[5]")
    RABIO_BUTTON_CONDITION = (By.XPATH, ".//div[@class='radioUnput_inputRegular__FbVbr']")
    PUBLISH_BUTTON = (By.XPATH, ".//button[text()='Опубликовать']")
    MY_ADVERTISEMENTS = (By.XPATH, "//*[@id='root']/div/div[2]/div[4]")
    CARDS_NAME = (By.XPATH, ".//div[@class='about']/h2")